@echo off
rem Easier to launch client...
rem -Sheriff

echo Launching localhost client...
echo Game is in french...
echo ===============================
D:/Panda3Ds/Panda3D-1.8.0/python/python.exe main.py -svaddr localhost -l fr
echo ===============================
echo Client ended...
pause